CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    code VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(64) NOT NULL
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id INTEGER NOT NULL REFERENCES categories(id); 